# Generated by Django 5.0.5 on 2024-05-15 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topic",
            new_name="Bug",
        ),
    ]
