# Generated by Django 5.0.5 on 2024-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0002_rename_topic_bug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug",
            old_name="text",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="bug",
            name="id",
        ),
        migrations.AddField(
            model_name="bug",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="bug_attachments/"),
        ),
        migrations.AddField(
            model_name="bug",
            name="bug_id",
            field=models.AutoField(default="00000", primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="bug",
            name="description",
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bug",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="Medium",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="Medium",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ANALYZING", "Analyzing"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FIXED", "Fixed"),
                    ("RETEST", "Re-test"),
                    ("DONE", "Done"),
                ],
                default="New",
                max_length=12,
            ),
        ),
    ]
