# Generated by Django 5.0.5 on 2024-05-16 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_bug_log",
            "0003_rename_text_bug_title_remove_bug_id_bug_attachment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="bug_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
