# Generated by Django 5.0.5 on 2024-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0004_alter_bug_bug_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="bug_id",
            field=models.AutoField(default="00000", primary_key=True, serialize=False),
        ),
    ]
