# Generated by Django 5.0.5 on 2024-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0005_alter_bug_bug_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="urlhash",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
