# Generated by Django 5.0.5 on 2024-05-16 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0006_bug_urlhash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bug",
            name="urlhash",
        ),
    ]
