# Generated by Django 5.0.5 on 2024-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0009_alter_bug_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
