# Generated by Django 5.0.6 on 2024-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bug_log", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
